version: '3'
services:
  nginx:
    image: nginx
  redis:
    image: redis
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - SECRET_KEY_BASE=secret
      - DATABASE_URL=postgresql://dev:password@postgres:5432
