version: '3.2'
services:
  nginx:
    image: nginx:1.11.9
    volumes:
      - nginx_config:/etc/nginx/conf.d
      - type: bind
        source: ./public
        target: /app/public
      - type: bind
        source: ./certs
        target: /app/certs
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
  redis:
    image: redis
  app:
    build:
      context: .
      dockerfile: containers/production/Dockerfile
    env_file:
      - containers/production/.env
    command: containers/production/entrypoint
    volumes:
      - nginx_config:/etc/nginx/conf.d
      - type: bind
        source: .
        target: /app
    depends_on:
      - redis
    ports:
      - 3000:3000
  sidekiq:
    build:
      context: .
      dockerfile: containers/production/Dockerfile
    env_file:
      - containers/production/.env
    command: bash -c "bundle install && bundle exec sidekiq"
    volumes:
      - nginx_config:/etc/nginx/conf.d
      - type: bind
        source: .
        target: /app
    depends_on:
      - redis
  schedulex:
    build:
      context: .
      dockerfile: containers/production/Dockerfile.schedulex
    env_file:
      - containers/production/.env
    command: bash -c "mix deps.get && iex -S mix"
    volumes:
      - './schedulex:/app'
    depends_on:
      - redis

volumes:
  nginx_config:
    external: false
